name: golden_scenario_env
channels:
  - pytorch
  - fastai
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas=1.4.3
  - pandas-profiling=3.2.0
  - numpy=1.23.1
  - scikit-learn=1.1.2
  - matplotlib=3.5.2
  - matplotlib-base=3.5.2
  - matplotlib-inline=0.1.3
  - ipython=8.4.0
  - ipython_genutils=0.2.0
  - pydotplus=2.0.2
  - keras=2.6.0
  - keras-preprocessing=1.1.2
  - tensorflow=2.6.0
  - tensorflow-base=2.6.0
  - tensorflow-estimator=2.6.0
  - ipywidgets=7.7.1
  - ipykernel=6.15.1
  