name: golden_scenario_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas=1.4.3
  - numpy=1.23.1
  - pandas-profiling=3.2.0
  - matplotlib=3.5.2
  - ipython=8.4.0
  - ipywidgets=7.7.1
  - pydotplus=2.0.2
  - keras=2.6.0
  - scikit-learn=1.1.2
  - ipykernel=6.15.1
  - tensorflow=2.6.0